---
# tasks file for roles/lxd-c5-provision
- name: install nmap
  yum:
    name: nmap
    state: installed

- name: delete libpcap
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /lib64/libpcap.so.1
    - /lib64/libpcap.so.1.5.3
