---
# tasks file for roles/lxd-c8-provision
- name: install the apache packages
  yum:
    name: "{{ apache_packages }}"
    state: "installed"

- name: create the document root for the website
  file:
    dest: "{{ document_root }}"
    state: "directory"
    mode: "0755"
    owner: "apache"
    group: "{{ apache_group }}"

- name: set the permissions on the web folder
  file:
    dest: "{{ document_root }}"
    state: "directory"
    mode: "0755"
    owner: "apache"

- name: copy the vhost.conf to /etc/httpd/conf.d/
  template:
    src: "vhost.conf.j2"
    dest: "/etc/httpd/conf.d/vhost.conf"
  notify: "restart httpd"

- name: extract tickets.tgz into /var/www/webapp
  unarchive:
    src: tickets.tgz
    dest: "{{ document_root }}"
    mode: "0755"
    owner: "apache"
    group: "{{ apache_group }}"

- name: copy the HTML pages to the document root
  template:
    src: "{{ item }}.html.j2"
    dest: "{{ document_root }}/{{ item }}.html"
    mode: "0644"
    owner: "apache"
    group: "{{ apache_group }}"
  with_items:
    - index
    - sol

