---
- hosts: graylogg.example.com
  name: setup graylog server
  become: yes
  pre_tasks:
    - name: compare hostname with inventory
      fail: "msg='--- INCONSISTENT HOSTNAME: {{ ansible_nodename }} != {{ inventory_hostname }} ---'"
      when: ansible_nodename != inventory_hostname
  roles:
    - role: init
    - role: graylog-server
      vars:
        graylog_root_timezone: "Europe/Kiev"
        graylog_elasticsearch_shards: 1

