---
- hosts: c1
  name: setup graylog server
  become: no
  pre_tasks:
    - name: compare hostname with inventory
      fail: "msg='--- INCONSISTENT HOSTNAME: {{ ansible_nodename }} != {{ inventory_hostname }} ---'"
      when: ansible_nodename != inventory_hostname
  roles:
    - role: init
    - role: graylog-server
    - role: graylog-api
      vars:
        graylog_root_timezone: "Europe/Kiev"
        graylog_elasticsearch_shards: 1

