---
- name: "add graylog repo"
  yum:
    name: "{{ graylog_yum_rpm_url }}"
    state: "present"
    update_cache: True

- name: "install Graylog server"
  yum:
    name: "graylog-server"
    state: "present"
  notify: restart graylog-server

- name: "configure Graylog server"
  template:
    src: "graylog.server.conf.j2"
    dest: "/etc/graylog/server/server.conf"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- meta: "flush_handlers"

- name: "Wait for Graylog server to startup"
  uri:
    url: "{{ graylog_web_listen_uri }}"
    status_code: 200
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 5

