---
# tasks file for roles/lxd-c3-provision
- name: install the apache and ftp
  yum:
    name: "{{ packages }}"
    state: "installed"

- name: create the document root for the website
  file:
    dest: "{{ document_root }}"
    state: "directory"
    mode: "0755"
    owner: "apache"
    group: "{{ apache_group }}"

- name: set the permissions on the web folder
  file:
    dest: "{{ document_root }}"
    state: "directory"
    mode: "0755"
    owner: "apache"

- name: copy the vhost.conf to /etc/httpd/conf.d/
  template:
    src: "vhost.conf.j2"
    dest: "/etc/httpd/conf.d/vhost.conf"
  notify: reload daemons

- name: copy the test HTML page to the document root
  template:
    src: "index.html.j2"
    dest: "{{ document_root }}/index.html"
    mode: "0644"
    owner: "apache"
    group: "{{ apache_group }}"
  when: html_deploy

- name: change httpd unit file
  lineinfile:
    path: /usr/lib/systemd/system/httpd.service
    line: 'Requisite=vsftpd.service'
    insertafter: 'After=*'
  notify: reload daemons

- name: stop and disable ftp
  service:
    name: "vsftpd"
    state: "stopped"
    enabled: no

